# Generated by Django 5.2 on 2025-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, max_length=1),
        ),
    ]
