# Generated by Django 5.2 on 2025-12-11 17:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
