# Generated by Django 5.2 on 2025-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_reminder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
