# Generated by Django 6.0 on 2025-12-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_reminder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
