# Generated by Django 5.2 on 2025-12-08 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 آغاز شود و عدد باشد', regex='^09\\d{9}$')]),
        ),
    ]
